return {
  -- https://github.com/xiyaowong/transparent.nvim
  -- use :TransparentToggle to toggle transparency
  "xiyaowong/transparent.nvim",
  opts = {
    -- groups = { -- table: default groups
    -- "Normal",
    -- "NormalNC",
    -- "Comment",
    -- "Constant",
    -- "Special",
    -- "Identifier",
    -- "Statement",
    -- "PreProc",
    -- "Type",
    -- "Underlined",
    -- "Todo",
    -- "String",
    -- "Function",
    -- "Conditional",
    -- "Repeat",
    -- "Operator",
    -- "Structure",
    -- "LineNr",
    -- "NonText",
    -- "SignColumn",
    -- "CursorLine",
    -- "CursorLineNr",
    -- "StatusLine",
    -- "StatusLineNC",
    -- "EndOfBuffer",
    -- },
    exclude_groups = { "CursorLine" },
    -- extra_groups = { "RenderMarkdownCode" },
  },
}
